apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: orders
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000   # 7 days
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: fraud-alerts   # K8s object names can't contain underscores
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: fraud_alerts   # actual Kafka topic name - matches your ConfigMap's FRAUD_TOPIC
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000